[package]
name = "simple"
version = "0.1.0"
license = "MIT"
edition = "2021"
resolver = "2"

[dependencies]
ntex = { version = "0.7", features = ["tokio"] }
ntex-files = "0.3" 
oaph = {path = "../../"}
serde = {version = "1.0", features = ["derive"] }
